_BASE_: frame_maskformer2_v1_frame_R50_bs16.yaml
DATASETS:
  TRAIN: ("tabletop_syn_train",)
  TEST: ("tabletop_syn_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.00001
  STEPS: (20000, )
  MAX_ITER: 24000
  BACKBONE_MULTIPLIER: 0.1
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 300
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
MODEL:
  WEIGHTS: "./datasets/cache/model_final_94dc52_frame.pkl"
  META_ARCHITECTURE: "FrameMaskFormerV3"
  REID:
    ENCODER_TYPE: "linear"
    REID_NORMALIZE: True
    ENCODER_POS_TYPE: 'learned'
    # ENCODER_ONE_LAYER_AFTER_ATTENTION: True
    ENCODER_LAST_LAYER_BIAS: False
    # ENCODER_NUM_LAYERS: 3
    ENCODER_LAYER_STRUCTURE: ['cross', 'self', 'ffn', 'frame']
    ASSOCIATOR_LAYER_STRUCTURE: ['cross', 'self', 'ffn']
    ASSOCIATOR_LAYER_POSITION: 'in_detector'
    ASSOCIATOR_POS_EMBED: 'self_learned' # same_as_decoder, self_learned
    # ENCODER_UPDATE_CONFIDENCE: True
    ASSOCIATOR_DEC_LAYERS: 10
    ENCODER_NORMALIZE_BEFORE: False
    TEST_ASSOCIATOR: 'hungarian'
  MASK_FORMER:
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    # dim for unique
    REID_DIM: 256
    REID_WEIGHT: 1.
    INV_REID_WEIGHT: 1.
    REID_COEFF: 0.
    INV_REID_COEFF: 0.
    REID_SEQ_WEIGHT: 0.0
    INV_REID_SEQ_WEIGHT: 0.0
    REID_LOSS_OVER: 'matched'
    REID_FRAME_LOSS_TYPE: 'contrastive_cosdist'
    CLASS_SEQ_WEIGHT: 2.0
    # REID_DISTANCE_TYPE: 'cosine'
    REID_SOFTMAX_TEMPERATURE: 1.
    IGNORE_FIRST_OUTPUT: True
    TRANSFORMER_DECODER_NAME: "SequenceMultiScaleMaskedTransformerDecoderV2"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    FRAME_SEPARATE_OUTPUT: False
    DEEP_SUPERVISION: True
    DEEP_SUPERVISION_WEIGHT: 1.0
    NO_OBJECT_WEIGHT: 0.1
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.
    FRAME_DROPOUT: 0.
    FEAT_DROPOUT: 0.7
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    # query from last frame
    MEMORY_FORWARD_STRATEGY: 'none'
    TRACK_POS_TYPE: 'zero'
    TRACK_FEAT_TYPE: 'memory'
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
  SEM_SEG_HEAD:
    NAME: "FrameMaskFormerHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 1
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 16
INPUT:
  IMAGE_SIZE: 256
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "amazon_syn_v0"
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
  SAMPLING_FRAME_NUM: 2
  AUGMENTATIONS: ["brightness", "contrast", "saturation", "rotation"]