_BASE_: Base-Amazon-VideoInstanceSegmentation.yaml
MODEL:
  WEIGHTS: "model_final_94dc52.pkl"
  # META_ARCHITECTURE: "Vita"
  META_ARCHITECTURE: "FrameMaskFormerV2"
  MASK_ON: True
  REID:
    ENCODER_TYPE: "linear"
    REID_NORMALIZE: False 
    ENCODER_POS_TYPE: 'learned'
    # ENCODER_ONE_LAYER_AFTER_ATTENTION: True
    ENCODER_LAST_LAYER_BIAS: False
    # ENCODER_NUM_LAYERS: 3
    ENCODER_LAYER_STRUCTURE: ['cross', 'frame', 'self', 'ffn']
    # ENCODER_UPDATE_CONFIDENCE: True
    ENCODER_NORMALIZE_BEFORE: False
  SEM_SEG_HEAD:
    NAME: "FrameMaskFormerHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 1
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "SequenceMultiScaleMaskedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    # query from last frame
    MEMORY_FORWARD_STRATEGY: 'none'
    TRACK_POS_TYPE: 'zero'
    TRACK_FEAT_TYPE: 'memory'
    # dim for unique
    REID_DIM: 256
    REID_WEIGHT: 0.1
    INV_REID_WEIGHT: 0.1
    REID_COEFF: 0.
    INV_REID_COEFF: 0.
    REID_LOSS_OVER: 'matched'
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
  VITA:
    ENC_WINDOW_SIZE: 6
    SIM_WEIGHT: 0.5
DATASETS:
  DATASET_RATIO: [1.0, 0.8]
  TRAIN: ("amazon_video_syn_v2_train",)
  TEST: ("amazon_video_real_v1_test",)
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.00001
  STEPS: (14000,)
  MAX_ITER: 16000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
INPUT:
  SAMPLING_FRAME_NUM: 2
  SAMPLING_FRAME_RANGE: 8
  SAMPLING_FRAME_SHUFFLE: True
  # MIN_SIZE_TRAIN_SAMPLING : ["range", "choice", "range_by_clip", "choice_by_clip"]
  MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
  # RANDOM_FLIP : ["none", "horizontal", "flip_by_clip"]. "horizontal" is set by default.
  RANDOM_FLIP: "horizontal"
  AUGMENTATIONS: ["brightness", "contrast", "saturation", "rotation"]
  MIN_SIZE_TRAIN: (256,)
  MAX_SIZE_TRAIN: 256
  MIN_SIZE_TEST: 256
  MAX_SIZE_TEST: 256
  FORMAT: "RGB"
  CROP:
    ENABLED: False
    TYPE: "absolute_range"
    SIZE: (384, 600)
  # For pseudo videos
  PSEUDO:
    AUGMENTATIONS: ['rotation']
    MIN_SIZE_TRAIN: (288, 320, 352, 384, 416, 448, 480, 512)
    MAX_SIZE_TRAIN: 768
    CROP:
      ENABLED: True
      TYPE: "absolute_range"
      SIZE: (384, 600)
  LSJ_AUG:
    ENABLED: False
    IMAGE_SIZE: 768
    MIN_SCALE: 0.1
    MAX_SCALE: 2.0
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 16